[tool.isort]
profile = "black"
src_paths = ["src/requests", "test"]
honor_noqa = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"
minversion = "6.2"
testpaths = ["tests"]

[tool.mutmut]
paths_to_mutate = [ "src/requests/models.py" ]
tests_dir = [ "tests/" ]
